### ISSUE TITLE
Change DamLang.ini without any effect

### ISSUE THREAD

**Issue by Rik69** [digao-dalpiaz/Dam#1]
Hi,
I updated the DamLang.ini file, rebuild the component, rebuild the demo app without any effect.

What is the process to use an updated DamLang.ini file ?

Thank you

Erik

**Comment by digao-dalpiaz** [comment]
Hi, I'm sorry I did not see this issue before. I usually receive an e-mail from GitHub.

So, you just need to run the "Build Dam Resource.bat". This batch will re-build the RES file.
After that, please run the "AfterBuild.bat" to publish this RES file to the Lib folder.

Regards

**Comment by digao-dalpiaz** [comment]
Please let me know if any wrong word in the INI file, or new language support.
Thanks

**Comment by Rik69** [comment]
I tried to compile res after a .ini change without succes.
Dam_Resource.rc is not present in the folder so Build Dam Resource.bat crash.

**Comment by digao-dalpiaz** [comment]
Exactly, I had not seen that file was missing from GitHub.

I already put the file in the repository. Please try again now.
Thanks
