### ISSUE TITLE
Message aligment

### ISSUE THREAD

**Issue by Rik69** [digao-dalpiaz/Dam#2]
My I suggest you to align msg label in the center of the msg icon to replicate windows msg box.

![2019-02-08_150137](https://user-images.githubusercontent.com/125761/52503136-9bd34c80-2bb2-11e9-9815-0691aba08971.png)

**Comment by digao-dalpiaz** [comment]
Hey, great, It was implemented!

When all text height is smaller than icon, then the text will be centered horizontally. Oterwhise, it will be top aligned.
