### ISSUE TITLE
Message Link Event

### ISSUE THREAD

**Issue by narkotik42** [digao-dalpiaz/Dam#23]
How to catch click events in links added within the message. As far as I see, can you add not available?

**Comment by digao-dalpiaz** [comment]
Hello @narkotik42 

Yes, this event is not available. I'll include a new event in TDam container, allowing to handle link click.

Anyway, if the link is an URL (http://..., https://...), the default browser will open automatically with no event needed.

**Comment by narkotik42** [comment]
ok really thanks

**Comment by digao-dalpiaz** [comment]
Hello @narkotik42 

Please tell me if new Link Click event is working for you...

Best regards.
