### ISSUE TITLE
Dam message background color does not follows style.

### ISSUE THREAD

**Issue by Rik69** [digao-dalpiaz/Dam#29]
Hi,
Thank you for those super great components.
I noticed that the bkcolor of the message box does not follow style color when a style is applied.
I tried to force it by editing DAM dialog source, but it does not change anything.
In the following picturem message background should be white.

Erik

![2021-03-20_101747](https://user-images.githubusercontent.com/125761/111873370-6343f680-8966-11eb-9346-8ff8853aa3ba.png)

**Comment by digao-dalpiaz** [comment]
Hello @Rik69 ,

I'm testing here and it seems to be working with custom theme:

![custom_theme](https://user-images.githubusercontent.com/46692097/111904920-e6795100-8a27-11eb-9a7e-6069009920c9.png)

Could you please tell me what specific theme name you are using?

Thanks

**Comment by digao-dalpiaz** [comment]
Please, update to the new released version (4.13). 
Important: DzHTMLText component has been updated too.

**Comment by digao-dalpiaz** [comment]
Hello @Rik69 ,

Were you able to solve the problem with the themes?

**Comment by Rik69** [comment]
Hi
I use DelphiStyles VCL Style (Windows 10 Office Light)
You last change does not fix my problem, but If I uncheck StyleElements / seClients from the lbMsg (DamDialog), I can get a perfect dialog with with background.  
Thank you
Erik

**Comment by digao-dalpiaz** [comment]
Hello @Rik69 ,

OK, I see.
But it is strange, because the application should work with customized themes without needing this change in DamDialog.

Are you using Dam in a DLL module or BPL ? I mean, isolated from Application thread ?
