### ISSUE TITLE
Dam Example problem

### ISSUE THREAD

**Issue by limelect** [digao-dalpiaz/Dam#3]
Using D10.2.3
In Example Large Msg i have a Dam component
Within the component there is  _DamMsg2 and _DamMsg1
Sam with the other Demo.
I cannot see at DESIGN TIME a way to insert ANY msg into dam
i can see here and dfm
 TForm1 = class(TForm)
    Dam1: TDam;
    _DamMsg1: TDamMsg;
    _DamMsg2: TDamMsg;
    Button1: TButton;
But cannot add or delete any msg.
Cannot insert Right mouse on the component dose not help
you registered as RegisterNoIcon([TDamMsg]);

**Comment by digao-dalpiaz** [comment]
Hey there,

You just need to double-click at TDam component to open messages container form at design-time.

**Comment by limelect** [comment]
OK.But plz put that somewhere in help

**Comment by digao-dalpiaz** [comment]
It's described at "How to use" section, in the second paragraph.

But I think I will include popup menu item to manage messages on right-click too.
Thanks

**Comment by limelect** [comment]
And in the object inspector of the dam components.

Also one of the components is using html label which was not installed
yet. since i made an APK for ALL your components
it was a problem.

**Comment by digao-dalpiaz** [comment]
About Object Inspector:
You can only manage already created objects, like TDam and TDamMsg. If you want to copy, delete, manage them, you may use Structure tab. Bu I recommend you to use the Dam Messages Manager instead.

About Package:
You can embed all components in a single package, but ensure to recreate all registered components in a single Register procedure, using a design-time package.

**Comment by limelect** [comment]
OK
