### ISSUE TITLE
Also, the appearance of the buttons does not match the appearance of the buttons from the skin

### ISSUE THREAD

**Issue by digao-dalpiaz** [digao-dalpiaz/Dam#37]
Also, the appearance of the buttons does not match the appearance of the buttons from the skin

![Безымянный1](https://github.com/digao-dalpiaz/Dam/assets/26910229/201110c5-424b-49f7-94d5-c82bd930d713)
![Безымянный2](https://github.com/digao-dalpiaz/Dam/assets/26910229/d2ea94f3-fa92-45f3-927a-f57bdf0be2e4)

_Originally posted by @churchill123 in https://github.com/digao-dalpiaz/Dam/discussions/35_

**Comment by digao-dalpiaz** [comment]
Hello @churchill123,

Here in my tests, using Delphi themes, the dialog looks fine:
![image](https://github.com/digao-dalpiaz/Dam/assets/46692097/0dcfd955-da2b-4f0f-b89f-5155edd7fc70)

Are you using Delphi themes or some other 3rd Theme Component ?

**Comment by churchill123** [comment]
Здравствуйте, Rodrigo.

Вы писали 29 июля 2023 г., 21:57:29:
I use devExpress Skin Library
 
> Hello @churchill123,
> Here in my tests, using Delphi themes, the dialog looks fine:
> Are you using Delphi themes or some other 3rd Theme Component ?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

-- 
С уважением,
 Churchillphotos00002                         ***@***.***

-- 
Это сообщение было проверено антивирусным ПО Avast на наличие вирусов.
www.avast.com

**Comment by digao-dalpiaz** [comment]
OK, I don't have those components.
You could run a test there in your environment:

My component checks the background color of the text area based on this code:
`if TStyleManager.IsCustomStyleActive and (seClient in StyleElements) and not (csDesigning in ComponentState) then
      C.Brush.Color := TStyleManager.ActiveStyle.GetStyleColor(TStyleColor.scWindow)`

Please, check if TStyleManager.IsCustomStyleActive is True in Runtime, and what color you get in TStyleManager.ActiveStyle.GetStyleColor(TStyleColor.scWindow)

Thanks

**Comment by digao-dalpiaz** [comment]
Fixed this problem! Now the text area is transparent.
It will be available in the next version.
