### ISSUE TITLE
[dcc32 Error] Vcl.DamDialog.pas(249): E2003 Undeclared identifier: 'GeneratePlainText'

### ISSUE THREAD

**Issue by Rik69** [digao-dalpiaz/Dam#39]
Hi, I just dowloaded the latest version of DAM + DzHTMLText.
I deleted all files before replacing with new version.

I get a compilation error :  LbMsg.GeneratePlainText := True; from Vcl.DamDialog.pas (line 249)

Erik

**Comment by Rik69** [comment]
If I comment the previous line, I get : 
[dcc32 Error] Vcl.DamDialog.pas(658): E2003 Undeclared identifier: 'PlainText'

**Comment by Rik69** [comment]
Seems to be fixed.  I redownload the latest version of DzHTMLText.
Maybe I download the previous version just before you update it for the latest version of DAM.

Thank you for your wonderful components.

**Comment by digao-dalpiaz** [comment]
Hello,
OK.

_Just a reminder_: always prefer to download the version in the **Releases area**. 
Master sources may be being updated, while the Release version is the official version available.
