### ISSUE TITLE
DamLang.ini - Polish translation

### ISSUE THREAD

**Issue by jackdp** [digao-dalpiaz/Dam#4]
```
[Polish]
OK=OK
Yes=Tak
No=Nie
Info=Informacja
Quest=Zapytanie
Warn=Ostrzeżenie
Error=Błąd
Msg=Komunikat
```

![msg](https://user-images.githubusercontent.com/22514813/56933395-e72d3500-6ae7-11e9-8552-ee675ccc8e3b.png)

**Comment by digao-dalpiaz** [comment]
Hey Jacek,

Thanks for using my component.

I will be happy to add your translation to my component resource.
Please, include an Issue on GitHub with this translation information.

Best Regards
RODRIGO.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em seg, 29 de abr de 2019 às 20:36, Jacek Pazera <notifications@github.com>
escreveu:

**Comment by digao-dalpiaz** [comment]
Polish language support has been included in the component.
😉
