### ISSUE TITLE
Will there be a Lazarus version soon?

### ISSUE THREAD

**Issue by trinione** [digao-dalpiaz/Dam#8]
Hello,
Will there be a Lazarus version soon?

**Comment by digao-dalpiaz** [comment]
Hello @trinione,

Yes, I'm working on that.
There are some problems, like **TDesignWindow**. I could not find compatible class in Lazarus yet.

I will post my progress here at this issue.
Thanks.

**Comment by trinione** [comment]
Hi digao-dalpiaz,
Thanks. Hope you get thru! :) Lazarus is really picking up steam.

**Comment by digao-dalpiaz** [comment]
**The new version with Lazarus support is almost ready!**

![laz_dam](https://user-images.githubusercontent.com/46692097/95932322-f23e5880-0da1-11eb-80dc-9c2cee5d2455.png)

**Comment by digao-dalpiaz** [comment]
Done.
